name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Validate tag version
      run: |
        version=$(cat version.txt)        # get colony cli version
        tag=${GITHUB_REF/refs\/tags\//}   # get tag name
        tag="${tag:1}"                    # remove the 'v' prefix from the tag that triggered this action
        echo $version
        echo $tag
        if [ "$tag" == "$version" ]
        then
          echo "Tag and version are equal"
        else
          echo "Error: Tag and version are not equal"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install setuptools wheel twine

    - name: Build torque-cli
      run: |
        cd torque-cli
        python setup.py sdist bdist_wheel

    - name: Build colony-cli
      run: |
        cd colony-cli
        python setup.py sdist bdist_wheel

    - name: Create Release and Upload Artifacts torque-cli
      uses: softprops/action-gh-release@v1
      with:
        files: torque-cli/dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release and Upload Artifacts colony-cli
      uses: softprops/action-gh-release@v1
      with:
        files: colony-cli/dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Pypi torque-cli
      if: false #Temporary disable
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload torque-cli/dist/*

    - name: Publish to Pypi colony-cli
      if: false #Temporary disable
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload colony-cli/dist/*
